application: iamhapppy
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /resource
  static_dir: static
  
- url: /resource/css
  static_dir: static/css
  
- url: /resource/images/(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: main.py
